name: 推送有标签为v开头则以标签名称发布版本

on:
  push:
    tags:
      - "v*"
 
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: 拉取这个项目代码
        uses: actions/checkout@v2
 
      - name: 删除.git,.github文件夹与旗下的所有文件,获取变量TAG_NAME,ZIP_PATH 并创建压缩包
        run: |
          find . -name ".git" | xargs rm -Rf
          find . -name ".github" | xargs rm -Rf
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          pwd
          cd ..
          zip_path=$(pwd)
          echo "ZIP_PATH=$zip_path" >> $GITHUB_ENV
          zip -r ${{ github.event.repository.name }}.zip ./${{ github.event.repository.name }}
      
      - name: 创建一个以标签命名的版本
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHU_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: ${{ env.TAG_NAME }}
          body: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false

      - name: 上传压缩包到新版本
        uses: actions/upload-release-asset@v1
        id: upload_data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHU_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.ZIP_PATH }}/${{ github.event.repository.name }}.zip
          asset_name: ${{ github.event.repository.name }}.zip
          asset_content_type: application/zip
          
      - name: 消息字符串JSON格式化
        run: |
          contents="GITHUB\r\n仓库:${{github.repository}}\r\n发布:${{ env.TAG_NAME }}\r\n说明:${{ github.event.head_commit.message }}\r\n下载地址:${{ steps.upload_data.outputs.browser_download_url }}"
          json_var=$(php -r '$arr = array("msgtype" => "text","text" => array("content" => ""));$arr["text"]["content"] = "$contents";echo json_encode($arr);')
          echo "DD_CONTENTS=$json_var" >> $GITHUB_ENV
          
      - name: 给钉钉机器人发送消息
        env:
          WEBHOOK: ${{ secrets.DINGDING_WEBHOOK }}
        run: |
          curl -X POST \
            $WEBHOOK \
            -H 'Content-Type: application/json' \
            -d '${{ env.DD_CONTENTS }}'
