name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Check release version
        run: |
          version=$(git log --format=%B -n 1 ${{ github.sha }})
          if [[ $version == v* ]]; then
            echo "::set-output name=tag::${version}"
            echo "::set-output name=msg::${version:1}"
          else
            echo "Release version does not start with 'v'"
            exit 1
          fi

      - name: Create project folder
        run: mkdir ${{ github.repository }}

      - name: Copy files to project folder
        run: cp -r * ${{ github.repository }}

      - name: Compress project folder
        run: zip -r ${{ github.repository }}.zip ${{ github.repository }}

      - name: Upload release attachment
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ github.repository }}.zip
          asset_name: ${{ github.repository }}.zip
          asset_content_type: application/zip

      - name: Debug messages
        run: |
          echo "Tag: ${{ steps.check_release.outputs.tag }}"
          echo "Message: ${{ steps.check_release.outputs.msg }}"
          echo "Project folder: ${{ github.repository }}"
          echo "Zip file: ${{ github.repository }}.zip"

      - name: 给钉钉机器人发送消息
        env:
          WEBHOOK: ${{ secrets.DINGDING_WEBHOOK }}
        run: |
          curl -X POST \
            $WEBHOOK \
            -H 'Content-Type: application/json' \
            -d '{"msgtype": "text","text": {"content": "GITHUB\r\n仓库:${{github.repository}}\r\n发布:${{steps.get_version.outputs.VERSION}}\r\n说明:${{ github.event.head_commit.message }}\r\n下载地址:${{ steps.create_release.outputs.upload_url }}'
